version: v1
cluster:
  type: gke
  googleProjectId: foobar-1337
  clusterId: test-1
  zoneId: europe-west1-c
nodes:
  - id: node-1
    type: geth
    source: stable
  - id: node-2
    type: geth
    source: repo
    build: 65f1fbc
    options: "--cache 2048"
  - id: node-3
    type: parity
    source: provided
    chain: testnet