version: v1
cluster:
  type: gke
  googleProjectId: foobar-1337
  clusterId: test-1
nodes:
  - id: node-1
    type: geth-provided
  - id: node-2
    type: geth
    build: 65f1fbc
    features:
      - fast
      - reserved-only
    options: "--cache 2048"
  - id: node-3
    type: parity-provided
    chain: testnet