apiVersion: v1
kind: Service
metadata:
  labels:
    type: block-explorer-svc
  name: block-explorer-ui-svc
spec:
  ports:
    - port: 3000
      targetPort: 3000
      name: http-ui
  selector:
    shyft-app: block-explorer-ui
  type: ClusterIP
