apiVersion: v1
kind: Service
metadata:
  labels:
    type: block-explorer-svc
  name: block-explorer-api-svc
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http-api
  selector:
    shyft-app: block-explorer-api
  type: ClusterIP
