apiVersion: v1
kind: ReplicationController
metadata:
  name: ${id}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: shyft-block-frontend
        type: control
        shyft-app: block-explorer-frontend
    spec:
      containers:
        - name: nginx
          image: '${docker_reg}/${project_id}/nginx:latest'
          ports:
            - name: web-http
              containerPort: 80
