apiVersion: v1
kind: Service
metadata:
  labels:
    type: node-svc
  name: pg
  # name: node-${id}-svc
spec:
  ports:
    - port: 5432
      name: pg
  # - port: 8545
  # name: rpc
  selector:
    name: node-${id}
