apiVersion: v1
kind: ReplicationController
metadata:
  name: node-${id}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: node-${node_type}
        type: ${node_type}
    spec:
      containers:
        - name: nginx
          image: "${docker_reg}/${project_id}/${node_type}-${node_source}:latest"
          ports:
            - name: web-http
              containerPort: 80