apiVersion: v1
kind: ReplicationController
metadata:
  name: node-${id}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        type: node
        name: node-${id}
        node-type: ${node_type}
    spec:
      volumes:
        - name: blockchain
          gcePersistentDisk:
            pdName: ${id}-disk
            fsType: ext4
      containers:
        - name: geth
          image: "${docker_reg}/${project_id}/${node_type}-${node_source}:latest"
          ports:
            - name: rpc
              containerPort: 8545
            - name: p2p
              hostPort: 30303
              containerPort: 30303
          env:
            - name: NODE_OPTIONS
              value: "${node_options}"
          volumeMounts:
            - mountPath: /data
              name: blockchain