apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nginx
        type: control
    spec:
      containers:
        - name: nginx
          image: '${docker_reg}/${project_id}/nginx:latest'
          ports:
            - name: web-http
              containerPort: 80
